[build-system]
requires = ["setuptools>=61.0.0",
            "wheel"]

build-backend = "setuptools.build_meta"

[project]
name = "pyneoinstance"
version = "4.0.0"
description = "Handle Neo4j read and write transactions and provide methods for performing graph EDA"
readme = "README.md"
authors = [{ name = "Jose A. Alvarado-Guzman",email = "jose.alvarado-guzman@neo4j.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 5 - Production/Stable",
]
keywords = ["neo4j", "graph", "cypher"]
dependencies = [
    "neo4j-rust-ext>=5.0.0",
    "pandas>=1.3.0",
    "PyYAML>=5.1",
    "pyvis>=0.3.0",
    "neo4j-viz>=0.5.0"
]
requires-python = ">=3.10"

[project.optional-dependencies]
docs = ["mkdocs-material>=9.0.0", "mkdocstrings[python]>=0.24.0"]

[tool.setuptools.packages.find]
exclude = ["test*"]

[tool.setuptools.package-data]
pyneoinstance = ["py.typed"]

[project.urls]
Repository = "https://github.com/jose-alvarado-guzman/pyneoingest"
Documentation = "https://jose-alvarado-guzman.github.io/pyneoingest/"
